/**
 * A small slice of the real seeded catalogue (`packages/db/prisma/seed.ts`),
 * bundled so the UI is reviewable with no API and no database running.
 *
 * Two rules about this file:
 *  1. Every price string here was produced by the API's own `buildPriceDisplay`
 *     for the same seeded SKU — nothing was calculated in the browser, and
 *     nothing here is computed at runtime either. They are literals.
 *  2. Whenever it is used, the page MUST say so. `fetchCatalog` returns
 *     `source: 'sample'` and the layout renders a visible notice — a reviewer
 *     should never mistake this for live data.
 */
import type { CategoryView, ServiceView } from './types';

const SAMPLE_CATEGORY_NAMES: Record<string, string> = {
  LEAK: 'Leak & Pipe Repair',
  DRN: 'Drainage & Blockage',
  BTH: 'Bathroom Fittings',
  TNK: 'Tank, Motor & Pump',
  GYS: 'Water Heater / Geyser',
  PIP: 'New Installation & Pipelines',
};

const VISIT_149 = { visitChargePaise: '14900', visitChargeLabel: '₹149.00' };

export const SAMPLE_SERVICES: ServiceView[] = [
  {
    sku: 'PLB-LEAK-001',
    name: 'Tap / faucet leak repair',
    shortDesc: 'Tap / faucet leak repair',
    longDesc: null,
    categoryCode: 'LEAK',
    estDurationMin: 30,
    skillTier: 'L2',
    materialsPolicy: 'CONSUMABLES_ONLY',
    warrantyDays: 30,
    urgencyEligible: ['E2', 'E3'],
    requiredTools: [],
    preVisitQuestions: [],
    inspectFirst: false,
    price: {
      kind: 'FROM',
      amountPaise: '19900',
      amountLabel: '₹199.00',
      ...VISIT_149,
      headline: 'From ₹199.00',
      note: 'Starting price. Anything extra is quoted on site for your approval.',
    },
  },
  {
    sku: 'PLB-LEAK-002',
    name: "Tap replacement (customer's tap)",
    shortDesc: "Tap replacement (customer's tap)",
    longDesc: null,
    categoryCode: 'LEAK',
    estDurationMin: 30,
    skillTier: 'L2',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E2', 'E3'],
    requiredTools: [],
    preVisitQuestions: [],
    inspectFirst: false,
    price: {
      kind: 'EXACT',
      amountPaise: '24900',
      amountLabel: '₹249.00',
      ...VISIT_149,
      headline: '₹249.00',
      note: 'Fixed price for this service. Materials, if any, are quoted separately.',
    },
  },
  {
    sku: 'PLB-LEAK-004',
    name: 'Concealed leak detection (wall/floor)',
    shortDesc: 'Concealed leak detection (wall/floor)',
    longDesc: null,
    categoryCode: 'LEAK',
    estDurationMin: 60,
    skillTier: 'L3',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E1', 'E2', 'E3'],
    requiredTools: ['LEAK_DETECTOR'],
    preVisitQuestions: [
      { q: 'Where do you see dampness?', options: ['Ceiling', 'Wall', 'Floor', 'Near meter'] },
      { q: 'Is the floor below also affected?', options: ['Yes', 'No'] },
      { q: 'Has the water bill jumped recently?', options: ['Yes', 'No', 'Not sure'] },
      { q: 'Upload a photo/video of the damp patch (optional)', type: 'media', optional: true },
    ],
    inspectFirst: true,
    price: {
      kind: 'INSPECTION_FIRST',
      ...VISIT_149,
      headline: 'Price after inspection',
      note: 'Inspection ₹599.00, adjusted into the final bill. You approve the quote before any work starts.',
    },
  },
  {
    sku: 'PLB-LEAK-005',
    name: 'Concealed pipe repair (post-detection)',
    shortDesc: 'Concealed pipe repair (post-detection)',
    longDesc: null,
    categoryCode: 'LEAK',
    estDurationMin: 120,
    skillTier: 'L3',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E1', 'E2', 'E3'],
    requiredTools: [],
    preVisitQuestions: [],
    inspectFirst: true,
    price: {
      kind: 'QUOTE_ONLY',
      ...VISIT_149,
      headline: 'Price after site visit',
      note: 'No price is shown up-front. You receive an itemised quote on site and approve it before work begins.',
    },
  },
  {
    sku: 'PLB-DRN-001',
    name: 'Kitchen sink unclogging (manual)',
    shortDesc: 'Kitchen sink unclogging (manual)',
    longDesc: null,
    categoryCode: 'DRN',
    estDurationMin: 30,
    skillTier: 'L2',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E2', 'E3'],
    requiredTools: [],
    preVisitQuestions: [],
    inspectFirst: false,
    price: {
      kind: 'EXACT',
      amountPaise: '34900',
      amountLabel: '₹349.00',
      ...VISIT_149,
      headline: '₹349.00',
      note: 'Fixed price for this service. Materials, if any, are quoted separately.',
    },
  },
  {
    sku: 'PLB-DRN-004',
    name: 'WC blockage clearing',
    shortDesc: 'WC blockage clearing',
    longDesc: null,
    categoryCode: 'DRN',
    estDurationMin: 45,
    skillTier: 'L2',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E1', 'E2', 'E3'],
    requiredTools: ['CLOSET_AUGER'],
    preVisitQuestions: [
      { q: 'Is water draining slowly, or not at all?', options: ['Slowly', 'Not at all'] },
      { q: 'Is water overflowing onto the floor right now?', options: ['Yes', 'No'] },
      { q: 'Is this the only toilet in the house?', options: ['Yes', 'No'] },
      {
        q: 'Did anything get flushed that should not have been? (cloth / toy / sanitary item)',
        options: ['Yes', 'No'],
      },
    ],
    inspectFirst: false,
    price: {
      kind: 'EXACT',
      amountPaise: '49900',
      amountLabel: '₹499.00',
      ...VISIT_149,
      headline: '₹499.00',
      note: 'Fixed price for this service. Materials, if any, are quoted separately.',
    },
  },
  {
    sku: 'PLB-DRN-005',
    name: 'Sewer line jetting (external)',
    shortDesc: 'Sewer line jetting (external)',
    longDesc: null,
    categoryCode: 'DRN',
    estDurationMin: 120,
    skillTier: 'L3',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E1', 'E2', 'E3'],
    requiredTools: ['JETTING_UNIT'],
    preVisitQuestions: [],
    inspectFirst: false,
    price: {
      kind: 'FROM',
      amountPaise: '199900',
      amountLabel: '₹1,999.00',
      ...VISIT_149,
      headline: 'From ₹1,999.00',
      note: 'Starting price. Anything extra is quoted on site for your approval.',
    },
  },
  {
    sku: 'PLB-BTH-001',
    name: 'Tap installation',
    shortDesc: 'Tap installation',
    longDesc: null,
    categoryCode: 'BTH',
    estDurationMin: 20,
    skillTier: 'L2',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E2', 'E3'],
    requiredTools: [],
    preVisitQuestions: [],
    inspectFirst: false,
    price: {
      kind: 'PER_UNIT',
      amountPaise: '19900',
      amountLabel: '₹199.00',
      ...VISIT_149,
      headline: '₹199.00 per tap',
      note: 'Final amount depends on the quantity confirmed on site.',
    },
  },
  {
    sku: 'PLB-BTH-002',
    name: 'Shower / rain shower installation',
    shortDesc: 'Shower / rain shower installation',
    longDesc: null,
    categoryCode: 'BTH',
    estDurationMin: 45,
    skillTier: 'L2',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E2', 'E3'],
    requiredTools: [],
    preVisitQuestions: [],
    inspectFirst: false,
    price: {
      kind: 'EXACT',
      amountPaise: '39900',
      amountLabel: '₹399.00',
      ...VISIT_149,
      headline: '₹399.00',
      note: 'Fixed price for this service. Materials, if any, are quoted separately.',
    },
  },
  {
    sku: 'PLB-TNK-004',
    name: 'Pump repair / servicing',
    shortDesc: 'Pump repair / servicing',
    longDesc: null,
    categoryCode: 'TNK',
    estDurationMin: 90,
    skillTier: 'L3',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E1', 'E2', 'E3'],
    requiredTools: [],
    preVisitQuestions: [],
    inspectFirst: true,
    price: {
      kind: 'INSPECTION_FIRST',
      ...VISIT_149,
      headline: 'Price after inspection',
      note: 'Inspection ₹599.00, adjusted into the final bill. You approve the quote before any work starts.',
    },
  },
  {
    sku: 'PLB-GYS-004',
    name: 'Geyser repair (diagnosis)',
    shortDesc: 'Geyser repair (diagnosis)',
    longDesc: null,
    categoryCode: 'GYS',
    estDurationMin: 60,
    skillTier: 'L3',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E1', 'E2', 'E3'],
    requiredTools: [],
    preVisitQuestions: [],
    inspectFirst: true,
    price: {
      kind: 'INSPECTION_FIRST',
      ...VISIT_149,
      headline: 'Price after inspection',
      note: 'Inspection ₹299.00, adjusted into the final bill. You approve the quote before any work starts.',
    },
  },
  {
    sku: 'PLB-PIP-001',
    name: 'New bathroom plumbing (full)',
    shortDesc: 'New bathroom plumbing (full)',
    longDesc: null,
    categoryCode: 'PIP',
    estDurationMin: 480,
    skillTier: 'L3',
    materialsPolicy: 'EXCLUDED',
    warrantyDays: 30,
    urgencyEligible: ['E3'],
    requiredTools: [],
    preVisitQuestions: [],
    inspectFirst: true,
    price: {
      kind: 'QUOTE_ONLY',
      ...VISIT_149,
      headline: 'Price after site visit',
      note: 'No price is shown up-front. You receive an itemised quote on site and approve it before work begins.',
    },
  },
];

export const SAMPLE_CATEGORIES: CategoryView[] = Object.entries(SAMPLE_CATEGORY_NAMES).map(
  ([code, name]) => ({
    code,
    name,
    iconKey: null,
    serviceCount: SAMPLE_SERVICES.filter((s) => s.categoryCode === code).length,
  }),
);

export function sampleService(sku: string): ServiceView | undefined {
  return SAMPLE_SERVICES.find((s) => s.sku === sku);
}
